### ISSUE TITLE
problema en migasfree-launcher con el contenido de first-tags.conf

### ISSUE THREAD

**Issue by JordiRoman** [migasfree/migasfree-launcher#14]
Tras crear una iso con vx-create-iso y poniendo valores en /var/tmp/migasfree/first-tags.conf me encuentro con que siempre me da un error en la linea 35 de /usr/bin/migasfre-launcher "Se esperaba un operador binario"

 33 if [ "$_IS_FIRST_RUN" = "1" ] ; then
 34   _TAGS="$(cat $_FIRST)"
 35   if [ -z $_TAGS ] ; then
 36     _TAGS='""'
 37   fi

He probado con varios contenidos en el fichero (0,1 y 2 etiquetas) poniendo comillas simples y dobles y en el 80% de los casos tengo problemas 

La solución rápida para mi ha sido modificar la linea 35 colocando comillas a la variable

 35   if [ -z "$_TAGS" ] ; then

y rehacer paquete

¿Os habéis encontrado con este problema? o ¿es que simplemente soy mas torpe que dos zapatos izquierdos?

**Comment by agacias** [comment]
Cuando has creado la iso ¿Has utilizado la variable **MIGASFREE_TAGS** de **/etc/vx-createiso**?
El fichero /var/tmp/migasfree/first-tags.conf se genera con la información de esta variable.
Debes poner las  etiquetas entre comillas dobles, separadas por espacios y asegurarte que el nombre de  las etiquetas no tienen espacios. Por ejemplo: 
MIGASFREE_TAGS="SBR-EDUCACION_ESPECIAL SBR-EDUCACION_INFANTIL_Y_PRIMARIA" 
Tienes la ultima versión de ¿vx-create-iso?

**Comment by JordiRoman** [comment]
Si, he utilizado la variable MIGASFREE_TAGS  del script, la forma de uso queda bastante clara ya en los ejemplos que aparecen, el contenido del fichero generado (/var/tmp/migasfree/first-tags. también se ve correcto, la única diferencia, evidentemente, es que en el fichero no aparecen las comillas

--- /var/tmp/migasfree/first-tags ---
SW-ORACLE_JAVA_9 SW-VIRTUALBOX
--

La versión de vx-create-iso es la de github ( la 1.9-1 ) y la versión de migasfree-launcher (1.5-1  de Ubuntu14 ) la versión de migasfree-launcher que he usado para modificar es la 1.5-1 descargada de github

**Comment by agacias** [comment]
Mirando esto con un poco más de tranquilidad, resulta que es un bug que ocurre cuando pones mas de una etiqueta. La solución que aportas me parece acertada, ¡Gracias!
