### ISSUE TITLE
Avisar si es conveniente reiniciar para completar la actualización

### ISSUE THREAD

**Issue by jact** [migasfree/migasfree-launcher#16]
Mirar si se ha creado el fichero /var/run/reboot-required tras las actualizaciones para avisar si es adecuado reiniciar la máquina para que algunos cambios tengan lugar.

**Comment by agacias** [comment]
En https://github.com/migasfree/migasfree-launcher/issues/12 se borró auto-launch del schema com.ubuntu.update-notifier porque en trusty ya no existe, pero se ha revertido éste cambio en https://github.com/migasfree/migasfree-launcher/commit/8debf9283a8c4fb7f6ac50b6cac337adc5c19e36
