### ISSUE TITLE
Crear un setup.py

### ISSUE THREAD

**Issue by agacias** [migasfree/migasfree-launcher#25]
Para que se pueda instalar mediante:
`python setup.py --command-packages=stdeb.command bdist_deb`

**Comment by jact** [comment]
Esquema propuesto:

* AUTHORS
* INSTALL
* LICENSE
* VERSION
* README.md
* stdeb.cfg
* setup.py
* i18n
* data
** migasfree-launcher.conf
** migasfree-launcher.desktop
** sudo
*** migasfree-launcher
** img
*** *.svg
** org.migasfree.tray.gschema.xml
* debian
** postinst
* bin
** migasfree-launcher
* migasfree_tray
** __init__.py
** command_line.py
** console.py
** indicator.py

**Comment by jact** [comment]
Pero pienso que sería mejor idea crear un nuevo proyecto, llamado **migasfree-indicator**, y separar lo que es el indicador para el entorno gráfico de la lógica del script **migasfree-launcher**, que en todo caso, estaría mejor dentro del proyecto Vitalinux.

¿Qué piensas, Alberto?

**Comment by agacias** [comment]
Opino que /usr/bin/migasfree-launcher es bastante genérico (aunque eso si, sólo para sistemas debian y derivados). Lo que es propio de vitalinux (o de cualquier proyecto parecido) son los scripts que se añadirían a los directorios:
- /usr/share/migasfree-launcher/prerun.d
- /usr/share/migasfree-launcher/postrun.d
