### ISSUE TITLE
Añadir más iconos de estado al indicador

### ISSUE THREAD

**Issue by amartinr1977** [migasfree/migasfree-launcher#26]
Actualmente el indicador del cliente Migasfree (migasfree-tray/migasfree-launcher) que aparece en el Entorno de Escritorio sólo admite dos estados:

1. El logo de migasfree con un triángulo verde superpuesto indicando que se esta comunicando el cliente con el servidor Migasfree, 
2. y un logo de migasfree sin nada superpuesto que indica que la comunicación con el servidor Migasfree ha terminado.

Tal vez sería beneficioso para el usuario final que se añadieran más logos/estados para ese indicador, ya que la finalización de la comunicación con el servidor puede haber terminado en diferentes estados: no ha conseguido comunicarse, se ha comunicado pero se han detectado errores al actualizar la lista de repositorios, ha habido problemas/errores durante la instalación o configuración de paquetes, etc ...

Según lo anterior, podría ser una mejora el añadir mensajes al usuario y añadir nuevos estados del indicador para informar de aspectos que han sucedido durante la comunicación con el servidor.

**Comment by jact** [comment]
Vemos interesante añadir sólo 2 estados más:
* Uno para indicar que no ha sido posible la comunicación con el servidor de migasfree,
* y otro para informar que la sincronización no ha terminado con éxito (en la consola podrá observarse exactamente qué ha ocurrido).

**Comment by jact** [comment]
Finalmente, el indicador tiene 2 nuevos estados:

* Uno para indicar que ha habido un fallo en la conexión contra el servidor,
* y otro para indicar cualquier otra cosa que no sea un código de retorno cero (se mostrará en la consola el error correspondiente).
