### ISSUE TITLE
migasfree-launcher 1.12-1 no funciona en Lubuntu 14.04

### ISSUE THREAD

**Issue by amartinr1977** [migasfree/migasfree-launcher#28]
Nos sucede algo raro al instalar la nueva versión de migasfree launcher.  Os adjunto la salida que muestra cuando intento lanzar migasfree-tray desde la terminal:

**# migasfree-tray --interval 24
Traceback (most recent call last):
  File "/usr/bin/migasfree-tray", line 41, in <module>
    require_version('AppIndicator3', '0.1')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 79, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available**

Gracias de antemano por vuestra disposición y tiempo.
Saludos,
Arturo

**Comment by agacias** [comment]
¿ En qué sistema operativo ?

**Comment by amartinr1977** [comment]
En Lubuntu 14.04, que es lo que esta por debajo de Vitalinux. ¿Necesitas más información?

**Comment by jact** [comment]
Se ha comprobado el funcionamiento en LUbuntu 16.04 y no existe el problema que reportas, @amartinr1977.

Lo revisaremos en la versión 14.04.

**Comment by jact** [comment]
La versión de migasfree-launcher a la que te refieres, supongo que será la 1.12-1.

**Comment by jact** [comment]
Mientras tanto, ¿puedes verificar que los siguientes paquetes están instalados en la máquina donde te falla, @amartinr1977? 

* python-gi
* gir1.2-appindicator3-0.1
* gir1.2-gtk-3.0

**Comment by jact** [comment]
Revisando tu incidencia, @amartinr1977, veo que estás invocando el comando *migasfree-tray*. Dicho comando no se encuentra disponible en la versión 1.12-1, por lo que no sabemos qué versión de *migasfree-launcher* tienes instalada.

De todas formas, hemos probado la instalación en un Lubuntu 14.04, y el indicador funciona correctamente. También lo hemos probado en un Lubuntu-Vitalinux del 2016-03-14 y, desinstalando 2 paquetes que "comparten" ficheros con la versión anterior de *migasfree-launcher*, también se ejecuta sin el problema que relatas. El equipo que se ha registrado en vuestro servidor es el *3064*, por si queréis borrarlo.

**Comment by amartinr1977** [comment]
Perdonad de nuevo.  Os comento algo más:

(1) A raíz de que estamos actualizando la nueva versión del servidor migasfree, hemos visto que en el repo http://migasfree.org/pub/dists/wheezy/PKGS/ esta la versión de migasfree-launcher_1.12-1, de tal forma que me he puesto a continuar con ella para ver si con esa conseguía algo más.

(2) Tras arreglar algún problema de dependencias por malos vícios que he estado usando, lo he repaquetizado todo y lo he instalado: migasfree-cliente (4.10) y migasfree-launcher (1.12-1).

(3) Al iniciar sesión el equipo no se lanza el "migasfree-indicator".  Si lo lanzo desde terminal el resultado es el siguiente:

root@vitalinux:~# **migasfree-indicator --interval 24**
Traceback (most recent call last):
  File "/usr/bin/migasfree-indicator", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: migasfree-launcher==1.12

root@vitalinux:~# **dpkg -l migasfree-launcher**
Deseado=Desconocido/Instalar/Eliminar/Purgar/Retener
| Estado=No/Instalado/Config-files/Desempaquetado/Medio-conf/Medio-inst/espera-disparo/pendiente-disparo
|/ Err?=(ninguno)/Requiere-reinst (Estado,Err: mayúsc.=malo)
||/ Nombre               Versión         Arquitectura    Descripción
+++-====================-===============-===============-=============================================
ii  migasfree-launcher   1.12-1          all             UNKNOWN

root@vitalinux:~# **dpkg -l migasfree-client**
Deseado=Desconocido/Instalar/Eliminar/Purgar/Retener
| Estado=No/Instalado/Config-files/Desempaquetado/Medio-conf/Medio-inst/espera-disparo/pendiente-disparo
|/ Err?=(ninguno)/Requiere-reinst (Estado,Err: mayúsc.=malo)
||/ Nombre               Versión         Arquitectura    Descripción
+++-====================-===============-===============-=============================================
ii  migasfree-client     4.10-1          all             migasfree-client is a Python app to manage sy

(4) La verdad es que tras hacer un montón de pruebas no sabemos que hacer ya que nosotros de python no controlamos como para saber por donde pueden venir los problemas. **¿Se os ocurre algo?**

Muchas gracias de nuevo!!!

**Comment by amartinr1977** [comment]
Se me ha olvidado comentaros que los paquetes a los que hacéis referencia si que están instalados. Aprovecho para comentaros también que nosotros normalmente accedíamos a http://www.migasfree.org/repo/dists/Ubuntu14/PKGS/ para ver la últimas versiones de los paquetes que generáis, ya que supuestamente es el "repo" asociado a ubuntu14, y en ese no aparecen las últimas versiones ni de migasfree-client (hasta 4.9), ni de migasfree-launcher (hasta 4.11).  Tal vez sería conveniente que en ese repo aparecieran también las útlimas versiones que sacáis.  ¡¡Muchas gracias por vuestra disposición!!

root@vitalinux:~# **dpkg -l python-gi**
Deseado=Desconocido/Instalar/Eliminar/Purgar/Retener
| Estado=No/Instalado/Config-files/Desempaquetado/Medio-conf/Medio-inst/espera-disparo/pendiente-disparo
|/ Err?=(ninguno)/Requiere-reinst (Estado,Err: mayúsc.=malo)
||/ Nombre               Versión         Arquitectura    Descripción
+++-====================-===============-===============-=============================================
ii  python-gi            3.12.0-1ubuntu1 i386            Python 2.x bindings for gobject-introspection
root@vitalinux:~# **dpkg -l gir1.2-appindicator3-0.1**
Deseado=Desconocido/Instalar/Eliminar/Purgar/Retener
| Estado=No/Instalado/Config-files/Desempaquetado/Medio-conf/Medio-inst/espera-disparo/pendiente-disparo
|/ Err?=(ninguno)/Requiere-reinst (Estado,Err: mayúsc.=malo)
||/ Nombre               Versión         Arquitectura    Descripción
+++-====================-===============-===============-=============================================
ii  gir1.2-appindicator3 12.10.1+13.10.2 i386            Typelib files for libappindicator3-1.
root@vitalinux:~# **dpkg -l gir1.2-gtk-3.0**
Deseado=Desconocido/Instalar/Eliminar/Purgar/Retener
| Estado=No/Instalado/Config-files/Desempaquetado/Medio-conf/Medio-inst/espera-disparo/pendiente-disparo
|/ Err?=(ninguno)/Requiere-reinst (Estado,Err: mayúsc.=malo)
||/ Nombre               Versión         Arquitectura    Descripción
+++-====================-===============-===============-=============================================
ii  gir1.2-gtk-3.0       3.10.8-0ubuntu1 i386            GTK+ graphical user interface library -- gir

**Comment by agacias** [comment]
¿Puedes probar la instalación de *migasfree-launcher* en un Lubuntu limpio?

**Comment by amartinr1977** [comment]
Hola de nuevo a ambos ...

Tras hacer 1000 pruebas os comento:

(1) En un Lubuntu 14.04 limpio, tal como vosotros comentabais funciona sin problemas

(2) El mayor problema que teníamos es que hasta ahora hacíamos uso del migasfree-launcher de la comunidad, "vx-migasfree-launcher", y sobre ese nosotros instalábamos un "vx-dga-l-migasfree-launcher" para añadir las funcionalidades que veíamos que añadíais vosotros en vuestro paquete "migasfree-launcher" (todos nuestros paquetes empiezan por **vx-dga-l-** al ser paquetes de la distro vitalinux de la dga basada en "**l**ubuntu")

(3) Metiendo un "Conflicts" y "Replace" en nuestro paquete del "vx-migasfree-launcher" para poder instalar el vuestro, "migasfree-launcher", aparentemente tragaba pero luego no funcionaba, tal como os mostraba en los mensajes anteriores.

(4) Finalmente para solucionarlo me he descargado de vuestro github el código del paquete "migasfree-launcher" y he generado el paquete añadiendo al archivo "stdeb.cfg" lo siguiente:

Replace = vx-dga-l-migasfree-launcher (< 5.0), vx-migasfree-launcher
Conflicts = vx-dga-l-migasfree-launcher (< 5.0), vx-migasfree-launcher

No se por qué, el "Conflicts" lo coge sin problemas y lo introduce en el fichero "control" resultante del paquete, pero el "Replace" no.  Bueno, con esto, a funcionado, aunque pensaba que el "Replace" nos iba a hacer falta, al tener directorios/archivos comunes diferentes paquetes.

(5) Con todo lo anterior, he generado el "migasfree-launcher" a partir del vuestro, versión 1.13-1

(6) Ahora aparentemente todo va bien, pero he detectado que tras actualizarse contra migasfree el equipo cliente, el icono del migasfree-indicator desaparece (no se quita, sino que parece que no hay icono definido). Es decir, tal como se puede ver en la siguiente imagen, http://migasfree.educa.aragon.es/cosas-centros/incidencias/problema-logo-migasfree-indicator.png (espero que podáis apreciar lo que os digo), el icono/logo del migasfree-indicator esta pero no se corresponde con nada, esta en blanco.  Si pinchas con el botón derecho del ratón sobre ese "espacio en blanco" que deja el icono, como podéis ver se despliegan las opciones típicas: Consola, etc ...
¿Sabéis a qué es debido? ¿Tiene que ver con lo de los iconos que os solicitamos?

Ya perdonaréis tanto follón ... ¡¡Gracias!!

**Comment by jact** [comment]
Todavía no se ha hecho nada con la incidencia #26, así que no tiene nada que ver.

Mucho me temo que estará relacionado con el hecho de ejecutarse en un entorno LXDE y no en Gnome, que es donde lo probamos exhaustivamente nosotros.

Sería mejor crear otra incidencia al respecto y cerrar esta definitivamente, ya que está más relacionada con el arranque de la utilidad (y parece que ya se ha resuelto el misterio).

**Comment by jact** [comment]
Sobre la versión que le has puesto al paquete "retocado", @amartinr1977, te aconsejaría que por claridad modificases el último dígito en caso de reempaquetamiento. Así no habrá confusión con próximas versiones de _migasfree-launcher_.

Es decir, vuestro paquete para la versión *1.12*, debería ser *1.12-2*.

**Comment by amartinr1977** [comment]
Ok José Antonio!! Si no te importa, para evitar tener que buscar como hacerlo, ya me dirás como lo hago en un paquete python, ya que ya lo había probado a poner en el archivo "VERSION" 1.12-2, donde tenías puesto vosotros 1.13, y al ejecutar el comando que crea el paquete, "python setup.py --command-packages=stdeb.command bdist_deb", me ha crujido.  Es decir, ¿dónde indico que quiero que la versión del paquete que se genere sea la 1.12-2? Ya perdonarás mi ignorancia.  Al mismo tiempo, ¿se te ocurre el porque no añade el "Replace" en el archivo "control" resultante que añado en stdeb.cfg?
Intentaré probar alguna cosa más para ver que pasa con el icono del "migasfree-indicator" que no se ve una vez terminada la actualización, aunque de momento, tal como propones crearé una nueva "issue"/incidencia en vuestro github.
¡¡Mil Gracias!!

**Comment by jact** [comment]
Hay que modificar el campo **Debian-Version** del fichero **stdeb.cfg**.

Para tu segunda pregunta, consulta la documentación en http://pypi.python.org/pypi/stdeb/.
