### ISSUE TITLE
En entorno LXDE/Lubuntu 14.04 desaparece el icono de migasfree-indicator

### ISSUE THREAD

**Issue by amartinr1977** [migasfree/migasfree-launcher#29]
Tras actualizarse contra migasfree el equipo cliente (Lubuntu 14.04/Vitalinux EDU DGA), el icono del migasfree-indicator desaparece (ocupa un hueco vacío en la barra inferior de tareas, en la parte de indicadores, pero sin verse ningún icono definido). Es decir, tal como se puede ver en la siguiente imagen, http://migasfree.educa.aragon.es/cosas-centros/incidencias/problema-logo-migasfree-indicator.png (espero que podáis apreciar lo que os digo), el hueco que debería ocupar el icono/logo del migasfree-indicator está, pero no se corresponde con nada, esta en blanco/transparente. Si pinchas con el botón derecho del ratón sobre ese "espacio vacío" que deja el icono, como podéis ver se despliegan las opciones típicas: Consola, etc ...
¿Sabéis a qué es debido?

**Comment by jact** [comment]
En Lubuntu 16.04, el indicador muestra el icono correctamente.

En Lubuntu 14.04, el problema es que el tema de iconos por defecto (lubuntu), no tiene las _dependencias_ adecuadas en el fichero **index.theme**. En último término, debería heredar del tema *hicolor* y no es el caso.

Para solucionar el problema, hay que modificar el fichero **index.theme**, añadir la herencia de *hicolor* y reconstruir la caché del tema:

# update-icon-caches /usr/share/icons/lubuntu

**Comment by amartinr1977** [comment]
Joeerrr ... Me dejas planchado, vaya máquina estas hecho en el caso que la simple ejecución de ese comando solucione el problema.  ¿Me sugieres meter ese comando, update-icon-caches /usr/share/icons/lubuntu, en la post-instalación de nuestro vx-dga-l-migasfree-launcher?

**Comment by amartinr1977** [comment]
Se me olvidaba comentarte que es un comportamiento errático, es decir, a veces tras terminar de actualizarse el cliente se ve el icono de migasfree oscurecido (en negro) y a veces no.  Te lo comento por si te da más pistas de la posible solución. Perdona tantas molestias ...

**Comment by jact** [comment]
Sí, he observado ese comportamiento errático, incluso después de realizar las operaciones que te he comentado antes.

Sin embargo, no sé qué más podemos hacer desde _migasfree-launcher_. Lubuntu ya ha sacado nueva versión LTS (con nuevas versiones del entorno LXDE) y en ella nos deberíamos enfocar para que funcione. Si con una versión anterior de la aplicación funciona en la 14.04, seguiría con ella.

**Comment by amartinr1977** [comment]
Hola de nuevo!!

Hemos modificado (creemos que bien) el archivo "index.theme" que me sugieres para incluir en la lista de directorios la ruta "/usr/share/icons/hicolor/scalable/apps" (donde desempaquetáis los vuestros), pero no hace nada.  No obstante, el problema no vemos claro que sea ese ya que como te decimos a veces funciona y otras no.  Además lo que siempre se ve es el icono naranja de "migasfree.svg" que está en el paquete del migasfree-client en la misma donde los desempaqueta el "migasfree-launcher".  Es decir, que cuando le parece el icono "migasfree-idle-light.svg" se ve tras terminar la actualización contra migasfree, y en ocasiones no se ve.  Ya nos dirás si ves la luz en este asunto ya que estamos a punto de sacar una nueva versión de vitalinux con todos los cambios que habéis hecho.  En caso de que no te ocurra nada, no subiremos la versión del migasfree-launcher.
Gracias de nuevo y perdona toda la murga que te estamos dando. Saludos!!

**Comment by jact** [comment]
Como prueba, puedes añadir un icono propio, que se llame igual que el que debería aparecer, pero en formato PNG y ponerlo en el tema de iconos que hayáis seleccionado para el sistema, por si fuera un problema a la hora de leer el formato SVG.

No se me ocurre nada más.

**Comment by jact** [comment]
En algunos equipos antiguos con Ubuntu 12.04, también hemos observado este comportamiento, por lo que reabrimos la incidencia.
