### ISSUE TITLE
Idioma incorrecto (español en lugar de inglés) en Trusty y Xenial con LC_ALL=C en script migasfree-launcher

### ISSUE THREAD

**Issue by amartinr1977** [migasfree/migasfree-launcher#34]
Hola!!!

Comentaros un par de problemas que hemos detectado en relación a la parte del código siguiente:

if [ -f $_FIRST ]
then
    _TAGS="$(cat $_FIRST)"
    if [ -z "$_TAGS" ]
    then
        _TAGS='""'
    fi
    if [ "$SUDO_UID" = "999" ]
    then
        echo "--------------------------------"
        echo "It is testing LiveCD..."
    else
        echo "--------------------------------"
        **echo "Y" | LC_ALL=C migasfree --register**
        echo "Report tags: $_TAGS"
        /usr/bin/migasfree-tags --communicate $_TAGS
        echo "--------------------------------"
        echo "Synchronizing..."
        /usr/bin/migasfree --update "$_SYNC_ARGS"
        _RET=$?
        echo "--------------------------------"
...

1) El auto registro que hacéis en **echo "Y" | LC_ALL=C migasfree --register** no funciona ya que tenemos configurado el idioma como español.  Suelta un error en la consola de migasfree.  Para solucionarlo, al repaquetizar el paquete, hemos tenido que hacer lo siguiente:

**echo "s" | LC_ALL=C migasfree --register**

2) Con las modificaciones que habéis hecho en las últimas versiones, si el archivo "/var/tmp/migasfree/first-tags.conf" esta vacío, cuando llega a la línea que tenéis en el código **/usr/bin/migasfree-tags --communicate $_TAGS** no salta al ventana de selección de etiquetas, tal como hacía antes, y tal como es de esperar.  El error debe venir en que $_TAGS no esta vacío sino que su valor es '""', lo cual hace que el comando migasfree-tags pase de mostrar la ventana.  Para solucionarlo seguimos recurriendo al trozo de código del cual hacías uso en versiones anteriores:

if [ -f $_FIRST ]
then
    _TAGS="$(cat $_FIRST)"
    if [ -z "$_TAGS" ]
    then
        _TAGS='""'
    fi
    if [ "$SUDO_UID" = "999" ]
    then
        echo "--------------------------------"
        echo "It is testing LiveCD..."
    else
		echo "--------------------------------"
		echo "s" | LC_ALL=C migasfree --register
		**if [ "$_TAGS" = '""' ] ; then**
		   echo "Configurando sabor a seleccionar:"
		   **/usr/bin/migasfree-tags --communicate**
		**else**
		   echo "Configurando sabor: $_TAGS"
		   **/usr/bin/migasfree-tags --communicate $_TAGS**
		**fi**
		echo "Synchronizing..."
		/usr/bin/migasfree --update "$_SYNC_ARGS"
...

De esta forma, el comportamiento es el esperado para nosotros, aunque no se si esto último es lo que deseáis vosotros para vuestros clientes.

Saludos máquinas!!!
Feliz Navidad!!

**Comment by jact** [comment]
Sobre el apartado 2 de la incidencia, está solucionado en migasfree/migasfree#192.
